# site properties and page defaults
title: The Oliynyk Lab
subtitle: 
description: In our lab, we explore intermetallics—compounds where metals and metalloids intersect. Our mission? To discover novel compounds, unravel their crystal structures, and see just how far these materials can go. By combining cutting-edge syntheses, characterization, and machine learning, we're pushing the boundaries of materials science, one intermetallic at a time.
header: images/chat.webp
footer: images/chat.webp
proofer: false

# site social media and other links
links:
  email: ao3014@hunter.cuny.edu
  orcid: 0000-0003-0732-7340
  google-scholar: UqfxBZcAAAAJ
  github: OliynykLab
  twitter: OliynykLab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
    # markdown files in /_courses
  - scope:
      type: "courses"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
    # generate page for each course
  courses:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
