- id: doi:10.21105/joss.07205
  type: paper
  description: cifkit provides higher-level functions and properties for coordination geometry and atomic
site analysis from .cif files, which are standard file formats for storing crystallographic data such
as atomic fractional coordinates, symmetry operations, and unit cell dimensions.
  date: 2024-11-15
  image: https://joss.theoj.org/papers/10.21105/joss.07205

  tags:
    - open science
    - collaboration